eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${server.port}

microservice:
  payment:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/savePayment
  order:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
